---
title: "Pivot Data Tidyr"
output: html_notebook
---

```{r libraries}
library(tidyverse)
```

```{r read-data}
df <- readxl::read_excel("/Users/rashawnhoward/Downloads/table_01_17_060120.xlsx",
                             sheet = 1)
head(df)
colnames(df) <- c("type",
                      "1990",
                      "1991",
                      "1992",
                      "1993",
                      "1994",
                      "1995",
                      "1996",
                      "1997",
                      "1998",
                      "1999",
                      "2000",
                      "2001",
                      "2002",
                      "2003",
                      "2004",
                      "2005",
                      "2006",
                      "2007",
                      "2008",
                      "2009",
                      "2010",	
                      "2011",	
                      "2012",	
                      "2013",	"2014",	"2015",	"2016",	"2017","2018","2019")

df %>%  head()

df %>% 
  filter(`1990`!=1990) -> df

df %>% 
  pivot_longer(`1990`:`2019`,names_to ="year", values_to = "value") -> df

df %>% 
  group_by(type) %>% 
  mutate(row = row_number()) %>% 
  pivot_wider(names_from = type,values_from="value") %>% 
  dplyr::select(-row) %>% 
  janitor::clean_names() %>% 
  mutate(year = as.numeric(year)) %>% 
  na.omit() -> df
  
```


